version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.1.3
    steps:
      - checkout
      - run: source /etc/profile && nix run nixpkgs.emacs nixpkgs.python --command python test-startup.py
